ALTER TABLE HR.OPP_T_SETTING_VARIATION DROP PRIMARY KEY CASCADE;

DROP TABLE HR.OPP_T_SETTING_VARIATION CASCADE CONSTRAINTS;

CREATE TABLE HR.OPP_T_SETTING_VARIATION (

VARIATION_ID                  NUMBER  NOT NULL,
SETTING_TYPE_ID               VARCHAR2(100 BYTE)  NOT NULL,
VALUE                         VARCHAR2(1000 BYTE)  NOT NULL
);



CREATE UNIQUE INDEX HR.OPP_PK_SETTING_VARIATION ON HR.OPP_T_SETTING_VARIATION
(VARIATION_ID,SETTING_TYPE_ID);

ALTER TABLE HR.OPP_T_SETTING_VARIATION ADD (
CONSTRAINT OPP_PK_SETTING_VARIATION
PRIMARY KEY
  (VARIATION_ID,SETTING_TYPE_ID)
  ENABLE VALIDATE
);