ALTER TABLE HR.OPP_T_SETTING_ENVIRONMENT DROP PRIMARY KEY CASCADE;

DROP TABLE HR.OPP_T_SETTING_ENVIRONMENT CASCADE CONSTRAINTS;

CREATE TABLE HR.OPP_T_SETTING_ENVIRONMENT (

ENV_ID                  VARCHAR2(10 BYTE)  NOT NULL,
SETTING_TYPE_ID             VARCHAR2(100 BYTE)  NOT NULL,
VALUE                  VARCHAR2(1000 BYTE)  NOT NULL
);



CREATE UNIQUE INDEX HR.OPP_PK_SETTING_ENVIRONMENT ON HR.OPP_T_SETTING_ENVIRONMENT
(ENV_ID,SETTING_TYPE_ID);

ALTER TABLE HR.OPP_T_SETTING_ENVIRONMENT ADD (
CONSTRAINT OPP_PK_SETTING_ENVIRONMENT
PRIMARY KEY
  (ENV_ID,SETTING_TYPE_ID)
  ENABLE VALIDATE
);