ALTER TABLE HR.OPP_T_SETTING_APPLICATION DROP PRIMARY KEY CASCADE;

DROP TABLE HR.OPP_T_SETTING_APPLICATION CASCADE CONSTRAINTS;

CREATE TABLE HR.OPP_T_SETTING_APPLICATION (

SETTING_TYPE_ID               VARCHAR2(100 BYTE)  NOT NULL,
VALUE                      VARCHAR2(1000 BYTE) 

);



CREATE UNIQUE INDEX HR.OPP_PK_SETTING_APPLICATION ON HR.OPP_T_SETTING_APPLICATION
(SETTING_TYPE_ID);

ALTER TABLE HR.OPP_T_SETTING_APPLICATION ADD (
CONSTRAINT OPP_PK_SETTING_APPLICATION
PRIMARY KEY
  (SETTING_TYPE_ID)
  ENABLE VALIDATE
);