ALTER TABLE HR.OPP_T_SETTING_TYPE DROP PRIMARY KEY CASCADE;

DROP TABLE HR.OPP_T_SETTING_TYPE CASCADE CONSTRAINTS;

CREATE TABLE HR.OPP_T_SETTING_TYPE (

SETTING_TYPE_ID         VARCHAR2(100 BYTE)  NOT NULL,
DESCRIPTION             VARCHAR2(1000 BYTE)  NOT NULL,
DATA_TYPE_ID            NUMBER  NOT NULL,
LOWEST_ALLOWED_LEVEL    VARCHAR2(100 BYTE),  
MULTI_VALUE_ALLOWED_FL     NUMBER(1) DEFAULT 0 NOT NULL

);


CREATE UNIQUE INDEX HR.OPP_PK_SETTING_TYPE ON HR.OPP_T_SETTING_TYPE
(SETTING_TYPE_ID);

ALTER TABLE HR.OPP_T_SETTING_TYPE ADD (
CONSTRAINT OPP_PK_SETTING_TYPE
PRIMARY KEY
  (SETTING_TYPE_ID)
  ENABLE VALIDATE
);