ALTER TABLE HR.OPP_T_DATA_TYPE DROP PRIMARY KEY CASCADE;

DROP TABLE HR.OPP_T_DATA_TYPE CASCADE CONSTRAINTS;

CREATE TABLE HR.OPP_T_DATA_TYPE (
DATA_TYPE_ID            NUMBER	NOT NULL,
NAME					VARCHAR2(1000 BYTE) NOT NULL,
CONVERTER_ID 			NUMBER 

);



CREATE UNIQUE INDEX HR.OPP_PK_DATA_TYPE ON HR.OPP_T_DATA_TYPE
(DATA_TYPE_ID);

ALTER TABLE HR.OPP_T_DATA_TYPE ADD (
CONSTRAINT OPP_PK_DATA_TYPE
PRIMARY KEY
  (DATA_TYPE_ID)
  ENABLE VALIDATE
);